name: "lightgbm_model"
backend: "fil"
max_batch_size: 0
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "input__1"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "input__2"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "input__3"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "input__4"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "input__5"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_INT64
    dims: [ 1 ]
  }
]
parameters [
  {
    key: "model_type"
    value: { string_value: "lightgbm" }
  },
  {
    key: "output_class"
    value: { string_value: "true" }
  },
  {
    key: "threshold"
    value: { string_value: "0.5" }
  }
]
